language: generic

branches:
  only:
    - master

os:
  - linux

env:
  global:
    # Set default python version to avoid repetition later
    - PYTHON_VERSION=2.7
    - SETUP_CMD="pytest -v tests"
    - BUILD_CMD="python setup.py install"
    - CONDA_DEPENDENCIES="cython numpy"
    - CONDA_CHANNELS='conda-forge'
    - NUMPY_VERSION=stable
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6


install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - eval $BUILD_CMD

script:
  - eval $SETUP_CMD
